#!/bin/bash

current="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dpkg -l exuberant-ctags >& /dev/null || sudo apt-get install exuberant-ctags
[ ! -e ~/dotfiles_old ] && mkdir ~/dotfiles_old


cd $current

[ ! -e vim/bundle/vundle ] && git clone https://github.com/gmarik/vundle.git vim/bundle/vundle

\ls | while read file;
do 
    [ "$file" = "dotfiles_setup" ] && continue
    localfile="$HOME/.$file"
    dotfile="$(readlink -f "$file" )"
    [ -e "$localfile" ] && mv -f "$localfile" ~/dotfiles_old
    ln -vs "$dotfile" "$localfile"
done

vim +BundleInstall +qall
