# vim:ft=ansible:
- hosts: all
  become: True
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Add sudoers users to wheel group
      user:
        name={{ lookup('env', 'USER') }}
        groups=wheel
        append=yes
        state=present
        createhome=yes
    - name: Cleanup old sudoers config
      file:
        state=absent
        path='/etc/sudoers.d/50_{{ lookup('env', 'USER') }}_sh'

